//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.24 at 11:00:54 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.wmi.amu.edu.pl", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package model2;
